### ISSUE TITLE
Blender 2.79 Support

### ISSUE THREAD

**Issue by Gnates** [mrwonko/Blender-Jedi-Academy-Tools#10]
Hello! I have not tried this addon yet but I wanted to know if you have any plans to update this addon for Blender 2.79.

Thank you for your time!

**Comment by mrwonko** [comment]
No, I have no such plans. There are also a couple of other things that could be done to improve the addons, but since I'm not using them anymore I have little interest in doing them myself.

**Comment by UnoYakshi** [comment]
I've started using the add-on with Blender 2.79 – doesn't seem it has any problems with different Blender versions. `_humanoid.gla` has been imported with no issues. Although, I have some problems with `base_path` and importing `.glm`, but it should be first-timer errors.

**Comment by mrwonko** [comment]
now that I've incorporated cagelight's changes, this should be done
