### ISSUE TITLE
Model looks different after import and re-export (Vertex Groups?)

### ISSUE THREAD

**Issue by ubz35** [mrwonko/Blender-Jedi-Academy-Tools#19]
Hi Wonko we were talking about the issue of vertex groups exportation in JKHub forums you wanted some files to examine if you want to looking them i uploaded here https://github.com/ubz35/Model

**Comment by mrwonko** [comment]
[This](https://jkhub.org/forums/topic/12306-model-looks-weird/) is aforementioned the JKHub topic.

**Comment by mrwonko** [comment]
I've opened both models in ModView and they look identical to me.
