### ISSUE TITLE
Rancor rhand_tag_bone misplaced

### ISSUE THREAD

**Issue by mrwonko** [mrwonko/Blender-Jedi-Academy-Tools#54]
Reportedly, importing the rancor model puts its right hand tag bone into the wrong place. Investigate. What's so special about it? Maybe the first frame is not the root pose? Could this be connected to #52 somehow?

**Comment by DT85** [comment]
Nothing is wrong with it. For some reason, it has a messed up "rest position" (bindpose/basepose) which is Raven's fault. I've also verified the same thing happens when importing the rancor in 3ds Max, and also verified with noesis using the data viewer.

**Comment by mrwonko** [comment]
That explains why it's not an issue in-game. Then the workaround is to import animations, and then at least it will be in the right place in pose mode.
