### ISSUE TITLE
Mesh Export fails on calc_normals_split attribute missing. | Blender 4.2

### ISSUE THREAD

**Issue by MoritzJT** [mrwonko/Blender-Jedi-Academy-Tools#67]
Exporting meshes with split normals fails in Blender:   File "JAG2GLM.py", line 556, in loadFromBlender
    mesh.calc_normals_split()
    ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Mesh' object has no attribute 'calc_normals_split'

Was that the name of a hidden attribute? If it was and it is from the face corner domain I might be able to populate it via geonodes - if not, then things are broken in Blender 4.2

**Comment by mrwonko** [comment]
Breaking change in 4.2, will need to adapt: <https://developer.blender.org/docs/release_notes/4.1/python_api/#mesh>

**Comment by mrwonko** [comment]
See also <https://github.com/SomaZ/Blender_BSP_Importer/commit/46515eb02982c9a15d9cf99f47e5b94c2f271964>

**Comment by MoritzJT** [comment]
> > Exporting meshes with split normals fails in Blender: File "JAG2GLM.py", line 556, in loadFromBlender mesh.calc_normals_split() ^^^^^^^^^^^^^^^^^^^^^^^ AttributeError: 'Mesh' object has no attribute 'calc_normals_split'
> > Was that the name of a hidden attribute? If it was and it is from the face corner domain I might be able to populate it via geonodes - if not, then things are broken in Blender 4.2
> 
> You aren't using the lastest version of the addon. This call has been removed some commits ago. [9cad90e](https://github.com/mrwonko/Blender-Jedi-Academy-Tools/commit/9cad90e0ecfd1fd616222c0500fc141fdb2d6ea2)

Thank you, indeed that's my bad - I didn't use the most recent version. Closing the issue.
